language: python
os: linux
dist: bionic

jobs:
  include:
    - dist: xenial
      python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    # - python: pypy3

install: pip -q install tox codacy-coverage codecov

script:
  - tox -e cover

after_success:
  - python-codacy-coverage -r coverage.xml
  - codecov
