dist: bionic
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  # - "pypy3"

install: pip -q install tox codacy-coverage codecov

script:
  - tox -e cover

after_success:
  - python-codacy-coverage -r coverage.xml
  - codecov
