module main;
import io;
var int i=0;
function void main()
{
    io.printlnmon("1st Hello world from PICORV32,");
    io.printlnmon("..compiled with ppci-riscv!");
    i+=1;
    io.printlnmon("2nd Hello world from PICORV32,");
    io.printlnmon("..compiled with ppci-riscv!");
    i+=1;
    io.printlnmon("3rd Hello world from PICORV32,");
    io.printlnmon("..compiled with ppci-riscv!");
    i+=1;
    while(true) {}
}